# Путь к папкам с логами
LogDirectoryMap:
  Map1: "E:/Go_project/logtest/test"
  Map2: "E:/Go_project/logtest/test2"

# Интевал сканирования папок
RescanInterval: 20

# Маска лог-файлов
FilePattern: "*.log"


# Настройки пакетной отправки
BatchSize: 100
BatchInterval: 20

# Конфигурация ClickHouse
ClickHouse:
  Address: "localhost:9000"
  Username: "admin"
  Password: "admin"
  Database: "logs_db"
  DefaultTable: "logs"
  Protocol: "tcp"
  TableMap:
    Map1: "table_for_Map1"
    Map2: "table_for_Map2"

ProcessedStorage: "redis"        # новая настройка: "file" или "redis"
Redis: # параметры подключения к Redis
  Host: "localhost"
  Port: 32768
  DB: 0
  Password: ""                   # если требуется пароль

Logging: # настройки логирования
  LogFile: "temp/error.log"
  SentryDSN: ""
  EnableSentry: true
  ConsoleLevel: "info"
  Level: "info" #  минимальный уровень для записи в файл/Sentry (debug, info, warn, error)
  SentryLevel: "warn"
  Environment: "production"
  Release: "v0.0.1"
  ServiceName: "log-pump"